git clone https://github.com/apple/swift-cmark s:\cmark
git clone https://github.com/apple/swift-clang s:\clang
git clone https://github.com/apple/swift-llvm s:\llvm
#git clone https://github.com/llvm-mirror/lld s:\lld
git clone https://github.com/apple/swift-compiler-rt s:\compiler-rt
git clone https://github.com/apple/swift s:\swift
git clone https://github.com/apple/swift-lldb s:\lldb
git clone https://github.com/apple/swift-corelibs-libdispath s:\swift-corelibs-libdispath
git clone https://github.com/apple/swift-corelibs-foundation s:\swift-corelibs-foundation
git clone https://github.com/apple/swift-package-manager s:\swiftpm
git clone https://github.com/apple/swift-llbuild s:\llbuild
